# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ConorHassanWebsite-',
                'doc_host': 'https://conorhassan.github.io',
                'git_url': 'https://github.com/conorhassan/ConorHassanWebsite-',
                'lib_path': 'ConorHassanWebsite_'},
  'syms': {'ConorHassanWebsite_.core': {'ConorHassanWebsite_.core.foo': ('core.html#foo', 'ConorHassanWebsite_/core.py')}}}
